WebApplication3/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Data;
using WebApplication3.Helpers;
using WebApplication3.Interface;
using WebApplication3.Models;
using WebApplication3.ViewModel;

namespace WebApplication3.Controllers
{
    public class ClubController : Controller
    {
        //here we are connecting to the database
        private readonly IClubRepos _clubRepos;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;


        public ClubController(IClubRepos clubRepos, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            //_context = context;
            _clubRepos = clubRepos;
            //_photoService = photoService;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
            
        }
        public async Task<IActionResult> Index()
        {
            //this code is for geting the whole data from the db table 
            // in this case we had send the data to the view
            /*List<Club> clubs = _context.Clubs.ToList();
            return View(clubs);*/
            IEnumerable<Club> clubs = await _clubRepos.GetAll();
            return View(clubs);

        }
        public async Task<IActionResult> Details(int id)
        {
            Club club = await _clubRepos.GetByIdAsync(id);
            return View(club);
        }

        //remmber that the view most had the same name 
        public IActionResult Create() 
        {
            //because the httpcontext will return huge amount of data
            //and we only need one object so we created an extention so
            //we acn easily grap this object 
            //in this way we will get the id without hitting the database
            var currentUser = _httpContextAccessor.HttpContext.User.GetUserId();
            var createClubVM = new CreateClubViewModel { AppUserId = currentUser };
            return View(createClubVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateClubViewModel clubVM)
        {
            //Whether the Form values are bound to the Model.
            //All the validations specified inside Model class using Data annotations have been passed.
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Photo Error");
            }
            else
            {
                /*_clubRepos.Add(club);
                return RedirectToAction("Index");*/
                var result = await _photoService.AddPhotoAsync(clubVM.Image);
                var club = new Club
                {
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = result.Url.ToString(),
                    ClubCategory = clubVM.ClubCategory,
                    AppUserId = clubVM.AppUserId,
                    Address = new Address
                    {
                        City = clubVM.Address.City,
                        State = clubVM.Address.State,
                        Street = clubVM.Address.Street
                    }
                };
                _clubRepos.Add(club);
                return RedirectToAction("Dashbord", "Index");



            }
            return View(clubVM);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var club = await _clubRepos.GetByIdAsync(id);
            if (club == null)return View("Error");

            var clubvm = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = club.AddressId,
                Address = club.Address,
                Image = club.Image,
                ClubCategory = club.ClubCategory

            };
            return View(clubvm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, CreateClubViewModel clubVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "failed to edit");
                return RedirectToAction("Edit", clubVM);
            }
          
                var userId = await _clubRepos.GetByIdAsyncNoTracking(id);
                if (userId != null)
                {
                    try
                    {
                        await _photoService.DeletePhotoAsync(userId.Image);
                    } catch (Exception ex)
                    {
                        ModelState.AddModelError("", "could not delet");
                        return View(clubVM);
                    }
                
                    var result = await _photoService.AddPhotoAsync(clubVM.Image);
                    var club = new Club
                {
                    Id = id,
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = result.Url.ToString(),
                    ClubCategory = clubVM.ClubCategory,
                    Address = new Address
                    {
                        City = clubVM.Address.City,
                        State = clubVM.Address.State,
                        Street = clubVM.Address.Street
                    }
                };
                _clubRepos.Update(club);
                return RedirectToAction("index");
            }

            else
             {
               return View(clubVM);
             }

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _clubRepos.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteClub(int id)
        {
            var clubDetails = await _clubRepos.GetByIdAsync(id);

            if (clubDetails == null)
            {
                return View("Error");
            }

            if (!string.IsNullOrEmpty(clubDetails.Image))
            {
                _ = _photoService.DeletePhotoAsync(clubDetails.Image);
            }

            _clubRepos.Delete(clubDetails);
            return RedirectToAction("Index");
        }

    }
}

WebApplication3/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using WebApplication3.Data;
using WebApplication3.Interface;
using WebApplication3.Models;
using WebApplication3.Repository;
using WebApplication3.ViewModel;

namespace WebApplication3.Controllers
{
    public class RaceController : Controller
    {
        //private readonly AppDb _context;
        private readonly IRaceRepos _raceRepos;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public RaceController(IRaceRepos raceRepos, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            //_context = context;
            _raceRepos = raceRepos;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult>  Index()
        {
            /*List<Race> races = _context.Races.ToList();
            return View(races);*/
            IEnumerable<Race> races = await _raceRepos.GetAll();
            return View(races);

        }
        public async Task<IActionResult> Details(int id)
        {
            // we used include in order to get access to aadress 
            /*Race race = _context.Races.Include(a=> a.Address).FirstOrDefault(c => c.Id == id);
            return View(race);*/
            Race race = await _raceRepos.GetIdByAsync(id);
            return View(race);
        }
        public IActionResult Create()
        {
            var currentUser = _httpContextAccessor.HttpContext.User.GetUserId();
            var createRaceVM = new CreatRaceViewModel { AppUserId = currentUser };
            return View(createRaceVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreatRaceViewModel raceVM )
        {
            if(!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Photo Error");
                //_raceRepos.Add(race);
                //return RedirectToAction("Index");
            }
            else
            {
                var result = await _photoService.AddPhotoAsync(raceVM.Image);
                var race = new Race
                {
                    Title = raceVM.Title,
                    Description = raceVM.Description,
                    Image = result.Url.ToString(),
                    RaceCategory = raceVM.RaceCategory,
                    AppUserId = raceVM.AppUserId,
                    Address = new Address
                    {
                        City = raceVM.Address.City,
                        State = raceVM.Address.State,
                        Street = raceVM.Address.Street
                    }
                };
                _raceRepos.Add(race);
                return RedirectToAction("Dashbord","Index");

            }
            return View(raceVM);
        }
    }
}

WebApplication3/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Interface;
using WebApplication3.ViewModel;

namespace WebApplication3.Controllers
{
    public class UsersController : Controller
    {
        private readonly IRunnersRepos _runnersRepos;

        public UsersController(IRunnersRepos runnersRepos) 
        { 
            _runnersRepos = runnersRepos;
        }
        
        public async Task<IActionResult> Index()
        {
            var runner = await _runnersRepos.GetAllRunners();
            List<RunnersViewModel> result = new List<RunnersViewModel>();   
            foreach(var user in runner)
            {
                var runnerVM = new RunnersViewModel()
                {
                    Id = user.Id,
                    UsreName = user.UserName,
                    Pace = user.Pace,
                    Mileage = user.Mileage
                    
                    
                };
                result.Add(runnerVM);
            }
            return View(result);
        }
        public async Task<IActionResult> Detail(string id)
        {
            var runner = await _runnersRepos.GetRunnersById(id);
            var runnerDetailVM = new RunnerDetailViewModel()
            {
                Id = runner.Id,
                UserName = runner.UserName,
                Pace = runner.Pace,
                Mileage = runner.Mileage,
                ProfileImageUrl=runner.ProfileImageUrl,
                State=runner.State,              
                City = runner.City


            };
            return View(runnerDetailVM);
        }
    }

}

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #5c5c5c;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="/Img/logo.svg" alt="" width="100" height="60" class="d-inline-block align-text-top">
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Running Sport Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Runners</a>
                            </li>
                            

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Index">Club</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Race" asp-action="Index">Race</a>
                        </li>
                        
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Dashbord" asp-action="Index">Dashbrod</a>
                                </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-danger" asp-area="" asp-controller="Account" asp-action="Logout">LogOut</a>
                            </li>
                                
                            }else{
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
                                </li>
                            } 
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>